### ISSUE TITLE
Lack of Documentation

### ISSUE THREAD

**Issue by OmiWakode** [privateai/deid-examples#11]
Hi,

I like this product a lot, but I am seriously confused between block vs allow, enable vs disable, filters vs entities. Is there any documentation that I can refer to? In this repo all I see is examples; no actual documentation could be found.
For example, what does "pattern" stand for, and what entity type is percentage??

Thank you!

**Comment by guyd** [comment]
Thanks for the feedback @OmiWakode.

You can access our documentation at this link: https://docs.private-ai.com/introduction/.
For the specific questions regarding the block/allow lists and the filtering you can take a look at the API specs [here](https://docs.private-ai.com/reference/latest/operation/process_text_v3_process_text_post/#!path=entity_detection&t=request).
However, the default API settings should work for most use cases. You only need to dive into the block/allow list and filters if you want to customize the results for your specific use cases.
