### ISSUE TITLE
Getting 401 Access denied with Prof Key but working with community key

### ISSUE THREAD

**Issue by upasana-mittal** [privateai/deid-examples#38]
Hi,

I am using PAIClient in Python and using this URL: "https://api.private-ai.com/deid/"
This works with community key but not with professional key.

Please look into it

 raise HTTPError(message)
requests.exceptions.HTTPError: The request returned with a 401 Access Denied

**Comment by a-guiducci** [comment]
Hi @upasana-mittal! The URL for professional is "https://api.private-ai.com/professional/"

Would you mind trying the example with this URL and let me know if that solves the issue?

**Comment by upasana-mittal** [comment]
> Hi @upasana-mittal! The URL for professional is "https://api.private-ai.com/professional/"
> 
> Would you mind trying the example with this URL and let me know if that solves the issue?

This worked!!! Thanks so much
